import { ExcerptType } from "@races/service/index";

export const nameAdjectives = [
  "cute",
  "affectionate",
  "agreeable",
  "amiable",
  "bright",
  "charming",
  "creative",
  "determined",
  "diligent",
  "diplomatic",
  "dynamic",
  "energetic",
  "friendly",
  "funny",
  "generous",
  "gregarious",
  "hardworking",
  "helpful",
  "kind",
  "likable",
  "loyal",
  "patient",
  "polite",
  "sincere",
  "amazing",
  "awesome",
  "blithesome",
  "excellent",
  "fabulous",
  "favorable",
  "fortuitous",
  "gorgeous",
  "incredible",
  "unique",
  "mirthful",
  "outstanding",
  "philosophical",
  "propitious",
  "remarkable",
  "splendid",
  "stellar",
  "upbeat",
  "stunning",
  "wondrous",
];

export const nameNouns = [
  "tiger",
  "lion",
  "elephant",
  "leopard",
  "panther",
  "cheetah",
  "wolf",
  "jaguar",
  "hyena",
  "giraffe",
  "deer",
  "zebra",
  "gorilla",
  "monkey",
  "chimpanzee",
  "bear",
  "wild boar",
  "hippo",
  "kangaroo",
  "rhino",
  "crocodile",
  "panda",
  "squirrel",
  "mongoose",
  "porcupine",
  "koala",
  "wombat",
  "meerkat",
  "otter",
  "hedgehog",
  "possum",
  "chipmunk",
  "raccoon",
  "jackal",
  "hare",
  "mole",
  "rabbit",
  "alligator",
  "oryx",
  "elk",
  "badger",
  "dinosaur",
  "pangolin",
  "mole",
  "okapi",
  "camel",
  "cat",
  "coyote",
  "bison",
  "aardvark",
  "antelope",
  "emu",
  "eagle",
  "eel",
  "armadillo",
  "beaver",
  "penguin",
  "bat",
  "chameleon",
  "bull",
  "chihuahua",
  "chinchilla",
  "hawk",
  "iguana",
  "ibis",
  "ibex",
  "cobra",
  "jellyfish",
  "goose",
  "walrus",
  "seal",
  "skink",
  "markhor",
  "falcon",
  "shark",
  "owl",
  "bulbul",
  "bobcat",
  "yak",
  "reindeer",
  "moose",
  "puma",
  "okapi",
  "marten",
  "caracal",
];

export const avatarArray = [
  "car1.png",
  "car2.png",
  "car3.png",
  "car4.png",
  "car5.png",
  "car6.png",
  "car7.png",
  "car8.png",
];

export const excerpts: ExcerptType[] = [
  // {
  //   title: "Jane Eyre",
  //   author: "Charlotte Bronte",
  //   body: "A lover finds his mistress asleep on a mossy bank; he wishes to catch a glimpse of her fair face without waking her. He steals softly over the grass, careful to make no sound; he pauses-fancying she has stirred : he withdraws; not for worlds would he be seen. All is still: he again advances: he bends above her; a light veil rests on her features: he lifts it, bends lower; now his eyes anticipate the vision of beauty-warm, and blooming, and lovely, in rest. How hurried was their first glance! But how they fix! How he starts! How he suddenly and vehemently clasps in both arms the form he dared not, a moment since, touch with his finger! How he calls aloud a name, and drops his burden, and gazes on it wildly! He thus grasps and cries, and gazes, because he no longer fears to waken by any sound he can utter-by any movement he can make. He thought his love slept sweetly: he finds she is stonedead.",
  //   year: 1899,
  // },

  {
    title: "Into the Wild",
    author: "Jon Krakauer",
    body: "He was unheeded, happy, and near to the wild heart of life. He was alone and young and wilful and wildhearted, alone amid a waste of wild air and brackish waters and the seaharvest of shells and tangle and veiled grey sunlight.",
  },

  {
    author: "Albert Einstein",
    body: "Our task must be to free ourselves... by widening our circle of compassion to embrace all living creatures and the whole of nature and it's beauty.",
  },

  {
    title: "Great Expectations",
    author: "Charles Dickens",
    body: `We went on in this way for a long time, and it seemed likely that we should continue to go on in this way for a long time, when one day Miss Havisham stopped short as she and I were walking, she leaning on my shoulder; and said with some displeasure,- "You are growing tall, Pip!" I thought it best to hint, through the medium of a meditative look, that this might be occasioned by circumstances over which I had no control.`,
    year: 2010,
  },

  {
    title: "Great Expectations",
    author: "Charles Dickens",
    body: `"And then, dear boy, it was a recompense to me, look'ee here, to know in secret that I was making a gentleman. The blood horses of them colonists might fling up the dust over me as I was walking; what do I say? I says to myself, 'I'm making a better gentleman nor ever you'll be! ... If I ain't a gentleman, nor ain't got no learning, I'm the owner of such. All on you owns stock and land; which on you owns a brought-up London gentleman?'"`,
    year: 2010,
  },

  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    body: `"Many people may be to blame for your unhappiness, but nobody is ever responsible for your unhappiness but you. This is because you always get to choose how you see things, how you react to things, how you value things. You always get to choose the metric by which to measure your experiences."`,
    year: 2016,
  },

  {
    author: "Pierre Teilhard de Chardin",
    body: "Someday, after mastering the winds, the waves, the tides and gravity, we shall harness for God the energies of love, and then, for a second time in the history of the world, man will have discovered fire.",
  },

  {
    author: "Adam Riess",
    body: "One of the most exciting things about dark energy is that it seems to live at the very nexus of two of our most successful theories of physics: quantum mechanics, which explains the physics of the small, and Einstein's Theory of General Relativity, which explains the physics of the large, including gravity.",
  },

  {
    title: "Please Look After Mom",
    author: "Kyung-Sook Shin",
    body: "All I wanted was for you to be free from everything. And with that freedom, you often showed me another world, so I wanted you to be even freer. I wanted you to be so free that you would live your life for other people.",
    year: 2008,
  },

  {
    title: "Assassin's Creed: The Secret Crusade",
    author: "Oliver Bowden",
    body: "Only a mind free of impediment is capable of grasping the chaotic beauty of the world. This is our greatest asset.",
  },

  {
    title: "Falling into You",
    author: "Jasinda Wilder",
    body: "But we have to learn to be free. We have to, Nell. Doesn't mean happy all the time, or okay all the time. It's okay not to be okay. I told you that, but I'm relearning it myself. But not being okay doesn't mean you stop living.",
    year: 2013,
  },

  {
    title: "Tests of general relativity",
    author:
      "Wikipedia - https://en.wikipedia.org/wiki/Tests_of_general_relativity",
    body: `Mercury deviates from the precession predicted from these Newtonian effects. This anomalous rate of precession of the perihelion of Mercury's orbit was first recognized in 1859 as a problem in celestial mechanics, by Urbain Le Verrier. His re-analysis of available timed observations of transits of Mercury over the Sun's disk from 1697 to 1848 showed that the actual rate of the precession disagreed from that predicted from Newton's theory by 38″ (arcseconds) per tropical century (later re-estimated at 43″ by Simon Newcomb in 1882).`,
  },

  {
    title: "GW1509014: LIGO Detects Gravitational Waves",
    author: "black-holes.org - https://www.black-holes.org/gw150914",
    body: "On 14 September 2015 at 4:50:45 AM Eastern standard time, LIGO detected its first gravitational waves.  The waves descended on Earth from the southern hemisphere, passed through the Earth, and emerged at the Earth's surface first at the LIGO interferometer in Livingston, Louisiana, and then, 7 milliseconds later, at the LIGO interferometer in Hanford, Washington",
  },

  {
    title:
      "Proceedings of the National Academy of Sciences of the United States of America, Volume 15, Issue 3, pp. 168-173",
    author: "Hubble, Edwin",
    body: "Distances of extra-galactic nebulae depend ultimately upon the application of absolute-luminosity criteria to involved stars whose types can be recognized. These include, among others, Cepheid variables, novae, and blue stars involved in emission nebulosity. Numerical values depend upon the zero point of the period-luminosity relation among Cepheids, the other criteria merely check the order of the distances.",
    year: 1929,
  },

  // {
  //   title: "Just a test text",
  //   author: "Dev",
  //   body: "Testing",
  // },
];
